version: 2

sources:
  - name: raw
    database: dev_db
    schema: hr
    tables:
      - name: employees
      - name: departments
      - name: nation
      - name: emp_1
      - name: orders_1
      - name: events
      - name: orders